In [2]:
import pandas as pd

path = "Emplid_And_Crse2023.csv"
df = pd.read_csv(path, dtype={"Emplid": str})

**Data Cleaning & Exploration**

In [3]:
print(df.shape)
display(df.head())
display(df.columns)

(4278, 14)

,CompletionTermDesc,Emplid,Crse ID,Term Descrshort,Subject,Catalog Nbr,Class Section,Session Descrshort,Crse Component Descrshort,Crse Descr,Unt Earned - Credits,Crse Grade Off - Grade Earned,Course Code,Outside UMSI
0,Winter 2023,00496232,17281,FA 2021,SI,588,2,Regular,Lecture,Fundamntls Hum Beh,3.0,W,SI 588,No
1,Winter 2023,00496232,17281,FA 2022,SI,588,1,Regular,Lecture,Fundamntls Hum Beh,3.0,A-,SI 588,No
2,Winter 2023,00496232,20401,WN 2022,SI,622,3,Regular,Lecture,Usab Eval & Needs,4.0,A,SI 622,No
3,Winter 2023,00496232,21400,WN 2022,SI,520,2,Regular,Lecture,Graphic Design,3.0,A-,SI 520,No
4,Winter 2023,00496232,22099,WN 2023,SI,658,1,Regular,Lecture,Info Architecture,3.0,A,SI 658,No

Index(['CompletionTermDesc', 'Emplid', 'Crse ID', 'Term Descrshort', 'Subject',
       'Catalog Nbr', 'Class Section', 'Session Descrshort',
       'Crse Component Descrshort', 'Crse Descr', 'Unt Earned - Credits',
       'Crse Grade Off - Grade Earned', 'Course Code', 'Outside UMSI'],
      dtype='str')

In [4]:
# Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("-", "")
)

# Clean Course_Code
df["Course_Code"] = df["Course_Code"].astype(str).str.strip()

display(df.columns)

Index(['CompletionTermDesc', 'Emplid', 'Crse_ID', 'Term_Descrshort', 'Subject',
       'Catalog_Nbr', 'Class_Section', 'Session_Descrshort',
       'Crse_Component_Descrshort', 'Crse_Descr', 'Unt_Earned__Credits',
       'Crse_Grade_Off__Grade_Earned', 'Course_Code', 'Outside_UMSI'],
      dtype='str')

**Data Analysis**

In [5]:
# Unique students
all_students = set(df["Emplid"].unique())
print(f"Number of Students: {len(all_students)}")

# Unique courses
print(f"Number of Unique Courses: {df['Course_Code'].nunique()}")

# Most popular courses
print("Most Popular Courses:")
print(df["Course_Code"].value_counts().head(10))

Number of Students: 259
Number of Unique Courses: 310
Most Popular Courses:
Course_Code
SI 699    247
SI 501    242
SI 681    199
SI 539    172
SI 582    158
SI 588    151
SI 622    150
SI 690    142
SI 520    133
SI 506    132
Name: count, dtype: int64

**MTOP & Capstone Course Count**

In [6]:
print(f"Students with SI 697 or SI 698: {df[df['Course_Code'].isin(['SI 697', 'SI 698'])]['Emplid'].nunique()}")

print("Counts for SI 699, SI 697, SI 698:")
print(df["Course_Code"].value_counts().reindex(["SI 699", "SI 697", "SI 698"], fill_value=0))

Students with SI 697 or SI 698: 11
Counts for SI 699, SI 697, SI 698:
Course_Code
SI 699    247
SI 697     10
SI 698     10
Name: count, dtype: int64

In [7]:
# SI 699 students
si699_students = set(df.loc[df["Course_Code"] == "SI 699", "Emplid"])
print("SI 699:", len(si699_students))

SI 699: 247

**Find MTOP Students**

In [8]:
# MTOP students
mtop_students = set(df.loc[df["Course_Code"].isin(["SI 697", "SI 698"]), "Emplid"])
print("MTOP:",mtop_students, len(mtop_students))

MTOP: {'03548176', '66076784', '42978962', '16723660', '64632066', '31759504', '51815320', '55261795', '45216061', '94371524', '23237089'} 11

**Find Students Who Have Taken Neither**

In [9]:
# Missing students
missing_students = all_students - (si699_students | mtop_students)
print("Missing Students:",missing_students, len(missing_students))

Missing Students: {'91764943', '21677264'} 2

In [10]:
# Courseload for students who took neither SI 699 nor SI 697/698
df[df["Emplid"].isin(missing_students)].sort_values(["Emplid","Course_Code"])

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,Unt_Earned__Credits,Crse_Grade_Off__Grade_Earned,Course_Code,Outside_UMSI
870,Winter 2023,21677264,38574,WN 2011,AMCULT,616,1,Regular,Lecture,Native Amer History,3.0,A,AMCULT 616,Yes
866,Winter 2023,21677264,1633,WN 2011,ENGLISH,473,2,Regular,Recitation,Topics Amer Lit,3.0,A-,ENGLISH 473,Yes
872,Winter 2023,21677264,41626,WN 2011,SI,572,1,Regular,Lecture,Database App Design,3.0,A,SI 572,No
867,Winter 2023,21677264,9731,FA 2010,SI,580,1,Regular,Lecture,Records & Archives,3.0,A-,SI 580,No
869,Winter 2023,21677264,22326,FA 2010,SI,581,1,First 7 Wk,Lecture,Preservation Admin,1.5,B+,SI 581,No
871,Winter 2023,21677264,39979,WN 2011,SI,623,1,Regular,Seminar,Outcome-Based Evals,3.0,A-,SI 623,No
874,Winter 2023,21677264,42838,FA 2010,SI,640,1,Regular,Lecture,Digital Lib & Archiv,3.0,B+,SI 640,No
875,Winter 2023,21677264,42840,FA 2010,SI,651,1,Scnd 7 Wk,Lecture,Physical Treatment,1.5,A-,SI 651,No
868,Winter 2023,21677264,21045,FA 2010,SI,666,1,Regular,Lecture,Org of Inf Resources,3.0,B,SI 666,No
873,Winter 2023,21677264,42207,WN 2011,SI,675,1,First 7 Wk,Lecture,Digitiz for Preserv,1.5,B+,SI 675,No
865,Winter 2023,21677264,1459,FA 2010,SI,690,13,Regular,Ind Study,Intern/Field Exper,2.0,S,SI 690,No
3885,Winter 2023,91764943,13083,FA 2022,EAS,787,1,First 7 Wk,Lecture,Metro Dynamic Studio,2.0,A,EAS 787,Yes
3886,Winter 2023,91764943,13083,FA 2022,EAS,787,101,Scnd 7 Wk,Lecture,Metro Dynamic Studio,2.0,B+,EAS 787,Yes
3888,Winter 2023,91764943,42104,FA 2022,SI,501,1,Regular,Lecture,Contextual Inq,3.0,A,SI 501,No
3890,Winter 2023,91764943,48500,FA 2022,SI,670,1,Regular,Lecture,Appld Machine Learng,3.0,A,SI 670,No
3889,Winter 2023,91764943,45930,FA 2022,SI,671,1,Regular,Lecture,Data Mining,3.0,A-,SI 671,No
3887,Winter 2023,91764943,40667,WN 2023,SI,681,1,Regular,Seminar,Intern/Field Seminar,3.0,S,SI 681,No

In [11]:
# Combine MTOP and missing students to get the full list of students to exclude
exclude_students = mtop_students.union(missing_students)
print("Students to Exclude:", len(exclude_students))
exclude_students

Students to Exclude: 13

{'03548176',
 '16723660',
 '21677264',
 '23237089',
 '31759504',
 '42978962',
 '45216061',
 '51815320',
 '55261795',
 '64632066',
 '66076784',
 '91764943',
 '94371524'}

**Narrow Dataset to Only Students who Have Taken SI 699**

In [12]:
exclude_students = mtop_students.union(missing_students)

df_filtered = df[~df["Emplid"].isin(exclude_students)].copy()
print(df_filtered["Emplid"].nunique())

246

In [13]:
si699_rows = df[df["Course_Code"] == "SI 699"]
print("SI 699 rows:", len(si699_rows))
print("SI 699 unique students:", si699_rows["Emplid"].nunique())

SI 699 rows: 247
SI 699 unique students: 247

In [14]:
si699_rows["Emplid"].value_counts().loc[lambda x: x > 1]

Series([], Name: count, dtype: int64)

In [15]:
overlap = si699_students & mtop_students
print("Overlap between SI 699 and MTOP:", len(overlap))
print(overlap)

Overlap between SI 699 and MTOP: 1
{'42978962'}

In [16]:
df[df["Emplid"] == "42978962"].sort_values("Course_Code")

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,Unt_Earned__Credits,Crse_Grade_Off__Grade_Earned,Course_Code,Outside_UMSI
1666,Winter 2023,42978962,15629,FA 2022,ANTHRCUL,993,1,Regular,Lecture,Gsi Training,1.0,S,ANTHRCUL 993,Yes
1672,Winter 2023,42978962,42104,FA 2021,SI,501,2,Regular,Lecture,Contextual Inq,3.0,A,SI 501,No
1677,Winter 2023,42978962,48129,WN 2022,SI,505,1,First 7 Wk,Lecture,Career/Intern Studio,1.0,S,SI 505,No
1675,Winter 2023,42978962,47246,FA 2021,SI,506,1,Regular,Lecture,Programming I,3.0,C+,SI 506,No
1680,Winter 2023,42978962,50162,WN 2023,SI,510,1,Regular,Lecture,Information Ethics,3.0,B,SI 510,No
1681,Winter 2023,42978962,50846,FA 2022,SI,512,1,Regular,Lecture,Change The Internet,3.0,B,SI 512,No
1668,Winter 2023,42978962,21400,WN 2022,SI,520,2,Regular,Lecture,Graphic Design,3.0,B-,SI 520,No
1671,Winter 2023,42978962,41935,WN 2022,SI,530,1,Regular,Lecture,Prin in Management,3.0,C+,SI 530,No
1673,Winter 2023,42978962,43210,FA 2022,SI,534,1,Regular,Lecture,Theories Soc Influen,3.0,A,SI 534,No
1669,Winter 2023,42978962,39178,WN 2022,SI,539,1,Regular,Lecture,Web Design,3.0,C,SI 539,No
1674,Winter 2023,42978962,44772,FA 2021,SI,582,2,Regular,Lecture,Intro Interac Design,3.0,B,SI 582,No
1667,Winter 2023,42978962,20401,WN 2022,SI,622,1,Regular,Lecture,Usab Eval & Needs,4.0,A-,SI 622,No
1670,Winter 2023,42978962,40667,WN 2022,SI,681,1,Regular,Seminar,Intern/Field Seminar,6.0,S,SI 681,No
1678,Winter 2023,42978962,49365,FA 2022,SI,697,69,Regular,Ind Study,Master's Thesis 1,3.0,S,SI 697,No
1676,Winter 2023,42978962,47901,WN 2023,SI,699,301,Regular,Lecture,MSI Mastery Courses,3.0,A+,SI 699,No
1679,Winter 2023,42978962,49755,WN 2023,SW,611,1,Regular,Lecture,Afrocntr Prac Afr Am,3.0,A,SW 611,Yes

**Define Required Courses by Track**

In [17]:
df_filtered = df[~df["Emplid"].isin(exclude_students)].copy()
print(f"\nFiltered student count: {df_filtered['Emplid'].nunique()}")

Filtered student count: 246

In [18]:
track_required_courses = {
    "BDA":   ["SI 507", "SI 544", "SI 618", "SI 671"],
    "UX":    ["SI 520"],                                         # only UX-unique
    "UCAD":  ["SI 579", "SI 664", "SI 669"],                    # SI 579 is shared
    "LAKES": ["SI 510", "SI 547", "SI 666", "SI 667",
              "SI 676", "SI 580", "SI 647"]
}

In [19]:
# Create flag columns FIRST
for track, courses in track_required_courses.items():
    df_filtered[f"{track}_Flag"] = df_filtered["Course_Code"].isin(courses).astype(int)

In [20]:
# Then aggregate
track_counts = df_filtered.groupby("Emplid").agg(
    BDA_Count=("BDA_Flag", "sum"),
    UX_Count=("UX_Flag", "sum"),
    LAKES_Count=("LAKES_Flag", "sum"),
    UCAD_Count=("UCAD_Flag", "sum")
)

track_counts.head()

          BDA_Count  UX_Count  LAKES_Count  UCAD_Count
Emplid
00496232          0         1            0           0
01034862          0         1            0           0
01071228          0         1            0           0
01304159          0         1            0           2
01546057          0         1            0           0

In [21]:
zero_track_students = track_counts[
    (track_counts["BDA_Count"] == 0) &
    (track_counts["UX_Count"] == 0) &
    (track_counts["LAKES_Count"] == 0) &
    (track_counts["UCAD_Count"] == 0)
]
print(zero_track_students)
print(len(zero_track_students), "students have zero required courses for any track.")

          BDA_Count  UX_Count  LAKES_Count  UCAD_Count
Emplid
14164752          0         0            0           0
39220401          0         0            0           0
40969781          0         0            0           0
42391029          0         0            0           0
52765102          0         0            0           0
52825703          0         0            0           0
54924837          0         0            0           0
58217242          0         0            0           0
60801599          0         0            0           0
62200322          0         0            0           0
64348770          0         0            0           0
67296380          0         0            0           0
68748584          0         0            0           0
70337408          0         0            0           0
73526405          0         0            0           0
77175377          0         0            0           0
89520025          0         0            0           0
90080804          0         0            0           0
97538663          0         0            0           0
19 students have zero required courses for any track.

In [22]:
# Create indicator columns for whether each course is in the required course list.
# Will later be summed per student to count how many required courses they took.
for track, courses in track_required_courses.items():
    df_filtered[f"{track}_flag"] = df_filtered["Course_Code"].isin(courses)

In [23]:
# Use the counts of required courses ("votes") to infer the most likely track.
# Calculate total votes, detect ties, and identify the track with the highest votes.
vote_cols = ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count"]

In [24]:
# total votes + max vote per student
total_votes = track_counts[vote_cols].sum(axis=1)
max_vote = track_counts[vote_cols].max(axis=1)

In [25]:
# how many tracks tied for the max
number_at_max = track_counts[vote_cols].eq(max_vote, axis=0).sum(axis=1)

In [26]:
# best guess track
best_guess = (
    track_counts[vote_cols]
    .idxmax(axis=1)
    .str.replace("_Count", "", regex=False)
)

In [27]:
# Initialize all students as "Unknown", then assign tracks based on vote results.
track_counts["Inferred_Track"] = "Unknown"
 
# 0 votes → Zero-track (Students with no required-course signals are labeled Zero-track)
track_counts.loc[total_votes.eq(0), "Inferred_Track"] = "Zero-track"
 
# If multiple tracks share the highest vote count, label as "Tie".
tie_mask = total_votes.gt(0) & number_at_max.gt(1)
track_counts.loc[tie_mask, "Inferred_Track"] = "Tie"
 
# non-ties → assign best guess
assign_mask = total_votes.gt(0) & number_at_max.eq(1)
track_counts.loc[assign_mask, "Inferred_Track"] = best_guess[assign_mask]
 
print(track_counts["Inferred_Track"].value_counts())

Inferred_Track
Tie           65
BDA           60
UX            51
UCAD          29
LAKES         22
Zero-track    19
Name: count, dtype: int64

In [28]:
tie_ids = track_counts[track_counts["Inferred_Track"] == "Tie"].index
print(track_counts.loc[tie_ids, ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count"]]
      .value_counts())

BDA_Count  UX_Count  LAKES_Count  UCAD_Count
0          1         1            0             13
2          0         0            2             11
0          1         0            1             10
1          1         0            0              7
                                  1              7
                     1            0              4
           0         0            1              4
2          1         0            2              2
0          1         1            1              2
1          0         1            1              2
           1         1            1              1
3          1         0            3              1
           0         0            3              1
Name: count, dtype: int64

**Resolve Ties**

In [29]:
# Drop point columns if they already exist (makes cell safe to rerun)
point_cols = ["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]
track_counts = track_counts.drop(columns=[c for c in point_cols if c in track_counts.columns])

In [30]:
# Comprehensive tiebreaker point system
UX_TIEBREAK    = ["SI 520", "SI 539", "SI 582", "SI 588", "SI 622"]
UCAD_TIEBREAK  = ["SI 579", "SI 664", "SI 669"]
BDA_TIEBREAK   = ["SI 608", "SI 630", "SI 649", "SI 650", "SI 670",
                  "SI 568"]   # SI 568 added: required BDA prereq per degree requirements
LAKES_TIEBREAK = ["SI 623", "SI 530", "SI 626", "SI 632", "SI 633", "SI 638",
                  "SI 583", "SI 643", "SI 552", "SI 519"]
                  # SI 626 added: listed as alternative to SI 530 for LAKES per degree requirements
 
df_filtered["UX_Points"]    = df_filtered["Course_Code"].isin(UX_TIEBREAK).astype(int)
df_filtered["UCAD_Points"]  = df_filtered["Course_Code"].isin(UCAD_TIEBREAK).astype(int)
df_filtered["BDA_Points"]   = df_filtered["Course_Code"].isin(BDA_TIEBREAK).astype(int)
df_filtered["LAKES_Points"] = df_filtered["Course_Code"].isin(LAKES_TIEBREAK).astype(int)
 
points = df_filtered.groupby("Emplid")[
    ["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]
].sum()
 
track_counts = track_counts.join(points, how="left")
track_counts[["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]] = (
    track_counts[["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]].fillna(0)
)

In [31]:
# Reassign tie students using all four track signals
tie_mask = track_counts["Inferred_Track"].isin(["Tie", "Manual"])
point_cols_map = ["BDA_Points", "UX_Points", "LAKES_Points", "UCAD_Points"]
col_to_track = {
    "BDA_Points":   "BDA",
    "UX_Points":    "UX",
    "LAKES_Points": "LAKES",
    "UCAD_Points":  "UCAD"
}
 
for idx in track_counts[tie_mask].index:
    row = track_counts.loc[idx, point_cols_map]
    max_pts = row.max()
    if max_pts == 0 or (row == max_pts).sum() > 1:
        track_counts.loc[idx, "Inferred_Track"] = "Tie"
    else:
        track_counts.loc[idx, "Inferred_Track"] = col_to_track[row.idxmax()]
 
print(track_counts["Inferred_Track"].value_counts())

Inferred_Track
UX            100
BDA            72
UCAD           30
LAKES          23
Zero-track     19
Tie             2
Name: count, dtype: int64

In [32]:
# Inspect any remaining unresolvable tie students
tie_ids = track_counts[track_counts["Inferred_Track"] == "Tie"].index
print(f"{len(tie_ids)} unresolvable tie students:\n")
 
for emplid in tie_ids:
    courses = sorted(df_filtered[df_filtered["Emplid"] == emplid]["Course_Code"].unique())
    print(f"{emplid}: {courses}")
    print(track_counts.loc[emplid, ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count",
                                     "BDA_Points", "UX_Points", "LAKES_Points", "UCAD_Points"]])
    print()

2 unresolvable tie students:

31778854: ['ENTR 599', 'SI 501', 'SI 520', 'SI 529', 'SI 612', 'SI 616', 'SI 669', 'SI 690', 'SI 699']
BDA_Count       0
UX_Count        1
LAKES_Count     0
UCAD_Count      1
BDA_Points      0
UX_Points       1
LAKES_Points    0
UCAD_Points     1
Name: 31778854, dtype: int64

97763533: ['EECS 409', 'SI 501', 'SI 505', 'SI 507', 'SI 539', 'SI 564', 'SI 568', 'SI 579', 'SI 618', 'SI 650', 'SI 664', 'SI 669', 'SI 670', 'SI 671', 'SI 681', 'SI 690', 'SI 699']
BDA_Count       3
UX_Count        0
LAKES_Count     0
UCAD_Count      3
BDA_Points      3
UX_Points       1
LAKES_Points    0
UCAD_Points     3
Name: 97763533, dtype: int64

In [33]:
# Show full course records for unresolvable tie students
df_filtered[df_filtered["Emplid"].isin(
    track_counts[track_counts["Inferred_Track"] == "Tie"].index
)]

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,...,UCAD_Flag,LAKES_Flag,BDA_flag,UX_flag,UCAD_flag,LAKES_flag,UX_Points,UCAD_Points,BDA_Points,LAKES_Points
1157,Winter 2023,31778854,1459,FA 2022,SI,690,390,Regular,Seminar,Intern/Field Exper,...,0,0,False,False,False,False,0,0,0,0
1158,Winter 2023,31778854,21400,FA 2022,SI,520,2,Regular,Lecture,Graphic Design,...,0,0,False,True,False,False,1,0,0,0
1159,Winter 2023,31778854,39081,WN 2023,SI,529,1,Regular,Lecture,Online Communities,...,0,0,False,False,False,False,0,0,0,0
1160,Winter 2023,31778854,42104,FA 2022,SI,501,2,Regular,Lecture,Contextual Inq,...,0,0,False,False,False,False,0,0,0,0
1161,Winter 2023,31778854,43863,FA 2022,SI,612,2,Regular,Lecture,Pervasv Interact Des,...,0,0,False,False,False,False,0,0,0,0
1162,Winter 2023,31778854,44798,WN 2023,ENTR,599,21,Regular,Lecture,Spec Topics Entr,...,0,0,False,False,False,False,0,0,0,0
1163,Winter 2023,31778854,46306,WN 2023,SI,616,1,Regular,Lecture,Adv Graphic Design,...,0,0,False,False,False,False,0,0,0,0
1164,Winter 2023,31778854,47901,WN 2023,SI,699,401,Regular,Lecture,MSI Mastery Courses,...,0,0,False,False,False,False,0,0,0,0
1165,Winter 2023,31778854,48487,FA 2022,SI,669,1,Regular,Lecture,Dev Mobile Exp,...,1,0,False,False,True,False,0,1,0,0
4192,Winter 2023,97763533,1459,WN 2023,SI,690,1,Regular,Seminar,Intern/Field Exper,...,0,0,False,False,False,False,0,0,0,0
4193,Winter 2023,97763533,9732,FA 2022,SI,650,1,Regular,Lecture,Informatn Retrieval,...,0,0,False,False,False,False,0,0,1,0
4194,Winter 2023,97763533,39178,FA 2021,SI,539,1,Regular,Lecture,Web Design,...,0,0,False,False,False,False,1,0,0,0
4195,Winter 2023,97763533,40667,WN 2022,SI,681,1,Regular,Seminar,Intern/Field Seminar,...,0,0,False,False,False,False,0,0,0,0
4196,Winter 2023,97763533,41626,WN 2022,SI,664,1,Regular,Lecture,Database App Design,...,1,0,False,False,True,False,0,1,0,0
4197,Winter 2023,97763533,42091,FA 2021,SI,618,1,Regular,Lecture,Data Man & Analysis,...,0,0,True,False,False,False,0,0,0,0
4198,Winter 2023,97763533,42104,FA 2021,SI,501,1,Regular,Lecture,Contextual Inq,...,0,0,False,False,False,False,0,0,0,0
4199,Winter 2023,97763533,45930,FA 2022,SI,671,1,Regular,Lecture,Data Mining,...,0,0,True,False,False,False,0,0,0,0
4200,Winter 2023,97763533,47640,FA 2021,SI,507,1,Regular,Lecture,Inter Programming,...,0,0,True,False,False,False,0,0,0,0
4201,Winter 2023,97763533,47901,WN 2023,SI,699,5,Regular,Lecture,MSI Mastery Courses,...,0,0,False,False,False,False,0,0,0,0
4202,Winter 2023,97763533,48129,WN 2022,SI,505,1,First 7 Wk,Lecture,Career/Intern Studio,...,0,0,False,False,False,False,0,0,0,0
4203,Winter 2023,97763533,48487,FA 2022,SI,669,1,Regular,Lecture,Dev Mobile Exp,...,1,0,False,False,True,False,0,1,0,0
4204,Winter 2023,97763533,48500,FA 2022,SI,670,1,Regular,Lecture,Appld Machine Learng,...,0,0,False,False,False,False,0,0,1,0
4205,Winter 2023,97763533,48539,WN 2023,EECS,409,1,Regular,Seminar,Data Science Sem,...,0,0,False,False,False,False,0,0,0,0
4206,Winter 2023,97763533,49601,FA 2021,SI,564,1,Regular,Lecture,SQL & Databases,...,0,0,False,False,False,False,0,0,0,0
4207,Winter 2023,97763533,50159,WN 2022,SI,579,1,Regular,Lecture,Bldg Interactive App,...,1,0,False,False,True,False,0,1,0,0
4208,Winter 2023,97763533,50663,WN 2022,SI,568,1,Regular,Lecture,Intro Appld Data Sci,...,0,0,False,False,False,False,0,0,1,0

In [34]:
# MANUAL OVERRIDE SECTION
# Review the output above and manually assign remaining tie students.
# Based on the classes each student has taken, determine the most likely track.
# Example (from 2022): track_counts.loc["02585323", "Inferred_Track"] = "BDA"
#
# Add your overrides below:
track_counts.loc["31778854", "Inferred_Track"] = "UX"
track_counts.loc["97763533", "Inferred_Track"] = "BDA"

# After overrides, confirm no more Ties (unless truly unresolvable)
print(track_counts["Inferred_Track"].value_counts())

Inferred_Track
UX            101
BDA            73
UCAD           30
LAKES          23
Zero-track     19
Name: count, dtype: int64

**Resolve Zero-Track**

In [35]:
# Identify students with zero required-course signals and list all courses they took
zero_ids = track_counts[track_counts["Inferred_Track"] == "Zero-track"].index
for emplid in zero_ids:
    courses = sorted(df_filtered[df_filtered["Emplid"] == emplid]["Course_Code"].unique())
    print(f"{emplid}: {courses}")
    print()

14164752: ['ENTR 599', 'SI 512', 'SI 588', 'SI 612', 'SI 627', 'SI 658', 'SI 690', 'SI 699']

39220401: ['ENTR 560', 'ENTR 599', 'SI 552', 'SI 559', 'SI 612', 'SI 690', 'SI 691', 'SI 699']

40969781: ['ENTR 500', 'IOE 548', 'SI 501', 'SI 506', 'SI 529', 'SI 534', 'SI 539', 'SI 582', 'SI 588', 'SI 622', 'SI 658', 'SI 681', 'SI 690', 'SI 699', 'TO 548']

42391029: ['BA 670', 'SI 501', 'SI 505', 'SI 506', 'SI 529', 'SI 539', 'SI 552', 'SI 582', 'SI 588', 'SI 612', 'SI 616', 'SI 622', 'SI 681', 'SI 690', 'SI 699']

52765102: ['ENTR 560', 'IOE 548', 'MO 512', 'SI 501', 'SI 504', 'SI 505', 'SI 506', 'SI 552', 'SI 559', 'SI 588', 'SI 612', 'SI 616', 'SI 622', 'SI 627', 'SI 681', 'SI 699', 'TO 548', 'TO 635', 'UARTS 560']

52825703: ['SI 501', 'SI 504', 'SI 505', 'SI 506', 'SI 537', 'SI 539', 'SI 582', 'SI 588', 'SI 612', 'SI 616', 'SI 617', 'SI 622', 'SI 631', 'SI 684', 'SI 688', 'SI 691', 'SI 699']

54924837: ['ENTR 550', 'ENTR 599', 'SI 501', 'SI 504', 'SI 559', 'SI 631', 'SI 643', 'SI 690', 'SI 699']

58217242: ['EAS 539', 'EDUC 771', 'ENTR 510', 'SI 501', 'SI 519', 'SI 539', 'SI 559', 'SI 582', 'SI 588', 'SI 610', 'SI 612', 'SI 622', 'SI 658', 'SI 659', 'SI 681', 'SI 690', 'SI 699', 'UARTS 560']

60801599: ['ENTR 550', 'MKT 613', 'SI 501', 'SI 505', 'SI 506', 'SI 538', 'SI 539', 'SI 552', 'SI 559', 'SI 582', 'SI 588', 'SI 612', 'SI 616', 'SI 622', 'SI 658', 'SI 681', 'SI 699']

62200322: ['ENTR 599', 'SI 501', 'SI 559', 'SI 563', 'SI 612', 'SI 616', 'SI 643', 'SI 690', 'SI 699']

64348770: ['SI 501', 'SI 506', 'SI 512', 'SI 529', 'SI 538', 'SI 539', 'SI 582', 'SI 588', 'SI 612', 'SI 616', 'SI 622', 'SI 631', 'SI 658', 'SI 681', 'SI 699']

67296380: ['ENTR 599', 'SI 501', 'SI 539', 'SI 582', 'SI 616', 'SI 622', 'SI 690', 'SI 699']

68748584: ['ELI 601', 'ENTR 550', 'MO 512', 'SI 504', 'SI 505', 'SI 506', 'SI 530', 'SI 539', 'SI 548', 'SI 552', 'SI 582', 'SI 588', 'SI 622', 'SI 631', 'SI 681', 'SI 684', 'SI 690', 'SI 699']

70337408: ['SI 501', 'SI 504', 'SI 505', 'SI 506', 'SI 534', 'SI 539', 'SI 552', 'SI 559', 'SI 582', 'SI 588', 'SI 612', 'SI 622', 'SI 623', 'SI 658', 'SI 681', 'SI 699']

73526405: ['ELI 532', 'ELI 534', 'IOE 548', 'SI 539', 'SI 559', 'SI 612', 'SI 622', 'SI 699', 'TO 548', 'URP 510', 'URP 535', 'URP 550', 'URP 570', 'URP 603']

77175377: ['ENTR 520', 'SI 501', 'SI 506', 'SI 529', 'SI 539', 'SI 548', 'SI 552', 'SI 559', 'SI 582', 'SI 588', 'SI 622', 'SI 643', 'SI 658', 'SI 681', 'SI 684', 'SI 699', 'UARTS 560']

89520025: ['SI 501', 'SI 512', 'SI 529', 'SI 538', 'SI 552', 'SI 612', 'SI 623', 'SI 690', 'SI 699']

90080804: ['ENGR 599', 'ENTR 500', 'MO 512', 'SI 501', 'SI 505', 'SI 529', 'SI 539', 'SI 552', 'SI 559', 'SI 582', 'SI 588', 'SI 616', 'SI 622', 'SI 631', 'SI 681', 'SI 686', 'SI 699', 'TO 616']

97538663: ['EDUC 737', 'SI 519', 'SI 542', 'SI 549', 'SI 552', 'SI 554', 'SI 564', 'SI 658', 'SI 686', 'SI 690', 'SI 699']

In [36]:
# Look at their most common courses
zero_courses = df_filtered[df_filtered["Emplid"].isin(zero_ids)]
print("Most common courses among zero-track students:")
print(zero_courses["Course_Code"].value_counts().head(20))

Most common courses among zero-track students:
Course_Code
SI 699       19
SI 690       16
SI 501       14
SI 622       13
SI 588       12
SI 612       12
SI 539       12
SI 582       11
SI 552       10
SI 559       10
SI 681       10
SI 506        9
SI 658        8
SI 616        8
ENTR 599      7
SI 505        7
SI 529        6
UARTS 560     6
SI 504        5
SI 631        5
Name: count, dtype: int64

In [37]:
# Soft-vote system to assign zero-track students using a broader course signal set
# Mirrors the tiebreaker lists above (SI 568 added for BDA, SI 626 added for LAKES)
zero_track_signals = {
    "UX":    ["SI 520", "SI 539", "SI 582", "SI 588", "SI 622"],
    "UCAD":  ["SI 579", "SI 664", "SI 669"],
    "BDA":   ["SI 608", "SI 630", "SI 649", "SI 650", "SI 670",
              "SI 568"],    # SI 568 added: required BDA prereq per degree requirements
    "LAKES": ["SI 510", "SI 547", "SI 666", "SI 667", "SI 676",
              "SI 580", "SI 647", "SI 530", "SI 626", "SI 552", "SI 538"]
              # SI 626 added: listed as alternative to SI 530 for LAKES
}

soft_votes = df_filtered[df_filtered["Emplid"].isin(zero_ids)].copy()
for track, courses in zero_track_signals.items():
    soft_votes[f"{track}_soft"] = soft_votes["Course_Code"].isin(courses).astype(int)
 
soft_votes = soft_votes.groupby("Emplid")[
    ["UX_soft", "UCAD_soft", "BDA_soft", "LAKES_soft"]
].sum()
print(soft_votes)

          UX_soft  UCAD_soft  BDA_soft  LAKES_soft
Emplid
14164752        1          0         0           0
39220401        0          0         0           1
40969781        4          0         0           0
42391029        4          0         0           1
52765102        2          0         0           1
52825703        4          0         0           0
54924837        0          0         0           0
58217242        4          0         0           0
60801599        4          0         0           2
62200322        0          0         0           0
64348770        4          0         0           1
67296380        3          0         0           0
68748584        4          0         0           2
70337408        4          0         0           1
73526405        2          0         0           0
77175377        4          0         0           1
89520025        0          0         0           2
90080804        4          0         0           1
97538663        0          0         0           1

In [38]:
# Take a closer look at students with 0 soft signals
zero_soft_ids = soft_votes[(soft_votes == 0).all(axis=1)].index.tolist()
print(f"Students with 0 soft signals: {zero_soft_ids}")
 
for emplid in zero_soft_ids:
    print(f"\n{'='*50}")
    print(f"Student: {emplid}")
    print(f"\nCourses taken:")
    print(sorted(df_filtered[df_filtered["Emplid"] == emplid]["Course_Code"].unique()))
    print(f"\nVote counts:")
    print(track_counts.loc[emplid, ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count",
                                     "BDA_Points", "UX_Points", "LAKES_Points", "UCAD_Points",
                                     "Inferred_Track"]])

Students with 0 soft signals: ['54924837', '62200322']

==================================================
Student: 54924837

Courses taken:
['ENTR 550', 'ENTR 599', 'SI 501', 'SI 504', 'SI 559', 'SI 631', 'SI 643', 'SI 690', 'SI 699']

Vote counts:
BDA_Count                  0
UX_Count                   0
LAKES_Count                0
UCAD_Count                 0
BDA_Points                 0
UX_Points                  0
LAKES_Points               1
UCAD_Points                0
Inferred_Track    Zero-track
Name: 54924837, dtype: object

==================================================
Student: 62200322

Courses taken:
['ENTR 599', 'SI 501', 'SI 559', 'SI 563', 'SI 612', 'SI 616', 'SI 643', 'SI 690', 'SI 699']

Vote counts:
BDA_Count                  0
UX_Count                   0
LAKES_Count                0
UCAD_Count                 0
BDA_Points                 0
UX_Points                  0
LAKES_Points               1
UCAD_Points                0
Inferred_Track    Zero-track
Name: 62200322, dtype: object

In [39]:
# Assign zero-track students based on soft votes
soft_col_to_track = {
    "UX_soft": "UX",
    "UCAD_soft": "UCAD",
    "BDA_soft": "BDA",
    "LAKES_soft": "LAKES"
}
 
soft_assignments = {}
for emplid, row in soft_votes.iterrows():
    max_votes = row.max()
    if max_votes == 0 or (row == max_votes).sum() > 1:
        soft_assignments[emplid] = "Manual"
    else:
        soft_assignments[emplid] = soft_col_to_track[row.idxmax()]

In [40]:
# --- MANUAL OVERRIDES FOR ZERO-TRACK STUDENTS ---
# Review the students labeled "Manual" above and assign them based on their
# full course history. Update the lines below as needed.
# Example (from 2022): soft_assignments["23497908"] = "UX"
#
soft_assignments["54924837"] = "UCAD"
soft_assignments["62200322"] = "UX"
print(soft_assignments)

{'14164752': 'UX', '39220401': 'LAKES', '40969781': 'UX', '42391029': 'UX', '52765102': 'UX', '52825703': 'UX', '54924837': 'UCAD', '58217242': 'UX', '60801599': 'UX', '62200322': 'UX', '64348770': 'UX', '67296380': 'UX', '68748584': 'UX', '70337408': 'UX', '73526405': 'UX', '77175377': 'UX', '89520025': 'LAKES', '90080804': 'UX', '97538663': 'LAKES'}

In [41]:
# Apply soft assignments to track_counts
for emplid, track in soft_assignments.items():
    track_counts.loc[emplid, "Inferred_Track"] = track

In [42]:
# Final check — should show 0 Zero-track and 0 Tie
print(track_counts["Inferred_Track"].value_counts())
assert "Zero-track" not in track_counts["Inferred_Track"].values, "Still have Zero-track students!"

Inferred_Track
UX       116
BDA       73
UCAD      31
LAKES     26
Name: count, dtype: int64

**Elective Analysis**

In [43]:
# Re-merge finalized track labels into course dataset
track_labels = track_counts.reset_index()[["Emplid", "Inferred_Track"]]
df_with_tracks = df_filtered.merge(track_labels, on="Emplid", how="left")
 
print(df_with_tracks["Inferred_Track"].value_counts())
print(f"Unique students: {df_with_tracks['Emplid'].nunique()}")

Inferred_Track
UX       1919
BDA      1224
UCAD      528
LAKES     411
Name: count, dtype: int64
Unique students: 246

In [44]:
# Required courses per track + universal exclusions
REQUIRED = {
    "BDA":   {"SI 507", "SI 544", "SI 618", "SI 671", "SI 504", "SI 568"},
    "UX":    {"SI 520", "SI 539", "SI 582", "SI 588", "SI 622"},  # shared with UCAD included
    "UCAD":  {"SI 579", "SI 664", "SI 669", "SI 539",
              "SI 582", "SI 588", "SI 622", "SI 504"},                       # shared with UX included
    "LAKES": {"SI 510", "SI 547", "SI 666", "SI 667",
              "SI 676", "SI 580", "SI 647"}
}

In [45]:
# Universal exclusions: prereqs, internship, capstone
UNIVERSAL_EXCLUDE = {"SI 501", "SI 505", "SI 506",
                     "SI 681", "SI 690", "SI 699"}
 
results = {}
for track in ["BDA", "UX", "UCAD", "LAKES"]:
    exclude = UNIVERSAL_EXCLUDE | REQUIRED[track]
    n_students = (track_counts["Inferred_Track"] == track).sum()
 
    track_df = df_with_tracks[
        (df_with_tracks["Inferred_Track"] == track) &
        (~df_with_tracks["Course_Code"].isin(exclude))
    ]
 
    elective_counts = (
        track_df.groupby("Course_Code")["Emplid"]
        .nunique()
        .sort_values(ascending=False)
        .rename("Student_Count")
        .reset_index()
    )
    elective_counts["Pct_of_Track"] = (
        elective_counts["Student_Count"] / n_students * 100
    ).round(1)
 
    results[track] = elective_counts
    print(f"\n── {track} (n={n_students} students) ──────────────────")
    print(elective_counts.head(10).to_string(index=False))

── BDA (n=73 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 564             58          79.5
     SI 670             49          67.1
     SI 664             44          60.3
     SI 649             43          58.9
     SI 650             43          58.9
     SI 539             37          50.7
     SI 630             28          38.4
     SI 579             28          38.4
     SI 608             17          23.3
     SI 582             13          17.8

── UX (n=116 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 612             71          61.2
     SI 559             51          44.0
     SI 658             49          42.2
     SI 616             38          32.8
     SI 552             36          31.0
     SI 529             30          25.9
     SI 504             28          24.1
     SI 579             20          17.2
     SI 684             18          15.5
   ENTR 599             18          15.5

── UCAD (n=31 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 520             22          71.0
     SI 507             17          54.8
     SI 564             10          32.3
     SI 559             10          32.3
     SI 649              9          29.0
     SI 612              9          29.0
     SI 631              9          29.0
     SI 659              7          22.6
     SI 618              7          22.6
     SI 658              6          19.4

── LAKES (n=26 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 623             17          65.4
     SI 633             14          53.8
     SI 632             14          53.8
     SI 504             11          42.3
     SI 585             10          38.5
     SI 583              9          34.6
     SI 530              9          34.6
     SI 519              9          34.6
     SI 643              9          34.6
     SI 581              8          30.8

In [46]:
print(df_with_tracks["Outside_UMSI"].value_counts())

Outside_UMSI
No     3575
Yes     507
Name: count, dtype: int64

In [47]:
outside_results = {}
for track in ["BDA", "UX", "UCAD", "LAKES"]:
    exclude = UNIVERSAL_EXCLUDE | REQUIRED[track]
    n_students = (track_counts["Inferred_Track"] == track).sum()
 
    outside_df = df_with_tracks[
        (df_with_tracks["Inferred_Track"] == track) &
        (~df_with_tracks["Course_Code"].isin(exclude)) &
        (df_with_tracks["Outside_UMSI"] == "Yes")
    ]
 
    outside_counts = (
        outside_df.groupby(["Course_Code", "Crse_Descr"])["Emplid"]
        .nunique()
        .sort_values(ascending=False)
        .rename("Student_Count")
        .reset_index()
    )
    outside_counts["Pct_of_Track"] = (
        outside_counts["Student_Count"] / n_students * 100
    ).round(1)
 
    outside_results[track] = outside_counts
    print(f"\n── {track} (n={n_students} students) ──────────────────")
    print(outside_counts.head(10).to_string(index=False))

── BDA (n=73 students) ──────────────────
Course_Code           Crse_Descr  Student_Count  Pct_of_Track
   EECS 402     Prog for Sci&Eng              4           5.5
   ENTR 560 Proj Mgmt Consulting              4           5.5
   EECS 545  Machine Learn (CSE)              4           5.5
   EECS 409     Data Science Sem              4           5.5
   ENTR 500  Intro to Innovation              3           4.1
   ENGR 599     Spec Topics Engr              3           4.1
   EECS 586           Algorithms              3           4.1
   EECS 559  Optim in Sig Pro ML              3           4.1
   EECS 505         Comp DS & ML              3           4.1
   EECS 494     Comp Game Design              3           4.1

── UX (n=116 students) ──────────────────
 Course_Code           Crse_Descr  Student_Count  Pct_of_Track
    ENTR 599     Spec Topics Entr             18          15.5
      BA 670       +Impact Studio             15          12.9
    ENTR 500  Intro to Innovation             14          12.1
    ENTR 560 Proj Mgmt Consulting             13          11.2
      MO 512  Bargain&Infl Skills             13          11.2
    ENTR 550 Interpersonal Skills             11           9.5
SURVMETH 600   Fund Surv Data Sci             10           8.6
     MKT 613    Consumer Behavior             10           8.6
    EDUC 618      XR for Learning              9           7.8
   UARTS 560    Grad ArtsEng Proj              9           7.8

── UCAD (n=31 students) ──────────────────
Course_Code           Crse_Descr  Student_Count  Pct_of_Track
  UARTS 560    Grad ArtsEng Proj              5          16.1
    IOE 548         Int Prod Dev              4          12.9
     TO 548        Integ Pro Dev              4          12.9
   EECS 494     Comp Game Design              4          12.9
   ENTR 500  Intro to Innovation              3           9.7
   ENTR 550 Interpersonal Skills              2           6.5
   EECS 598       Special Topics              2           6.5
   EECS 471     Applied GPU Prog              2           6.5
   ENTR 560 Proj Mgmt Consulting              1           3.2
   ENTR 599     Spec Topics Entr              1           3.2

── LAKES (n=26 students) ──────────────────
 Course_Code           Crse_Descr  Student_Count  Pct_of_Track
    ENTR 599     Spec Topics Entr              2           7.7
 MUSEUMS 498  Spec Museums Topics              2           7.7
ANTHRARC 497  Museum Anthropology              2           7.7
  HBEHED 671   Motivatnl Intvw PH              1           3.8
SURVMETH 630  Quest Design & Eval              1           3.8
 MUSEUMS 401    Issues in Museums              1           3.8
   LATIN 840 Classical Receptions              1           3.8
   LATIN 574      Later Latin Lit              1           3.8
   LATIN 506       Adv Latin Comp              1           3.8
 HISTORY 594    Topics in History              1           3.8

In [52]:
# Export full elective list for all tracks — for student-facing course directory
import json

full_course_map = {}

for track, df_result in results.items():
    # Only include SI courses (not outside UMSI)
    si_only = df_result[df_result['Course_Code'].str.startswith('SI ')]
    for _, row in si_only.iterrows():
        code = row['Course_Code']
        name = row.get('Crse_Descr') or row.get('Crse Descr') or ''
        if code not in full_course_map:
            full_course_map[code] = {'name': name, 'tracks': []}
        if track not in full_course_map[code]['tracks']:
            full_course_map[code]['tracks'].append(track)

# Print as JavaScript array ready to paste into your HTML file
print('const allCourses = [')
for code in sorted(full_course_map.keys(), key=lambda x: int(x.split()[1])):
    info = full_course_map[code]
    tracks = sorted([t.lower() for t in info['tracks']])
    tracks_str = ', '.join(f"'{t}'" for t in tracks)
    name = info['name'].replace("'", "\\'")
    print(f"  {{ code: '{code}', name: '{name}', tracks: [{tracks_str}] }},")
print('];')

const allCourses = [
  { code: 'SI 311', name: '', tracks: ['ux'] },
  { code: 'SI 425', name: '', tracks: ['ux'] },
  { code: 'SI 504', name: '', tracks: ['lakes', 'ux'] },
  { code: 'SI 507', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 510', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 511', name: '', tracks: ['bda'] },
  { code: 'SI 512', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 519', name: '', tracks: ['lakes', 'ux'] },
  { code: 'SI 520', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 529', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 530', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 534', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 536', name: '', tracks: ['ux'] },
  { code: 'SI 537', name: '', tracks: ['ux'] },
  { code: 'SI 538', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 539', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 540', name: '', tracks: ['lakes', 'ux'] },
  { code: 'SI 542', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 544', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 547', name: '', tracks: ['ux'] },
  { code: 'SI 548', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 549', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 552', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 554', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 559', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 561', name: '', tracks: ['bda'] },
  { code: 'SI 563', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 564', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 568', name: '', tracks: ['ucad'] },
  { code: 'SI 579', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 580', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 581', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 582', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 583', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 585', name: '', tracks: ['lakes'] },
  { code: 'SI 588', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 602', name: '', tracks: ['bda'] },
  { code: 'SI 605', name: '', tracks: ['lakes', 'ux'] },
  { code: 'SI 608', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 610', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 612', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 616', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 617', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 618', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 622', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 623', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 624', name: '', tracks: ['bda'] },
  { code: 'SI 626', name: '', tracks: ['lakes'] },
  { code: 'SI 627', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 630', name: '', tracks: ['bda', 'ucad'] },
  { code: 'SI 631', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 632', name: '', tracks: ['lakes'] },
  { code: 'SI 633', name: '', tracks: ['lakes'] },
  { code: 'SI 634', name: '', tracks: ['lakes'] },
  { code: 'SI 635', name: '', tracks: ['lakes'] },
  { code: 'SI 639', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 643', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 646', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 648', name: '', tracks: ['bda'] },
  { code: 'SI 649', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 650', name: '', tracks: ['bda', 'ucad'] },
  { code: 'SI 652', name: '', tracks: ['bda'] },
  { code: 'SI 657', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 658', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 659', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 661', name: '', tracks: ['bda'] },
  { code: 'SI 664', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 666', name: '', tracks: ['bda'] },
  { code: 'SI 669', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 670', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 671', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 682', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 684', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 686', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 688', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 691', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 702', name: '', tracks: ['lakes'] },
];