In [48]:
import pandas as pd

path = "Emplid_And_Crse2024.csv"
df = pd.read_csv(path, dtype={"Emplid": str})

**Data Cleaning & Exploration**

In [49]:
print(df.shape)
display(df.head())
display(df.columns)

(5125, 14)

,CompletionTermDesc,Emplid,Crse ID,Term Descrshort,Subject,Catalog Nbr,Class Section,Session Descrshort,Crse Component Descrshort,Crse Descr,Unt Earned - Credits,Crse Grade Off - Grade Earned,Course Code,Outside UMSI
0,Winter 2024,00348486,1459,FA 2023,SI,690,460,Regular,Seminar,Intern/Field Exper,1.0,S,SI 690,No
1,Winter 2024,00348486,16607,FA 2022,SI,544,1,Regular,Lecture,Intr Stat&Data Analy,3.0,A+,SI 544,No
2,Winter 2024,00348486,17271,FA 2022,TO,572,1,First 7 Wk,Recitation,App B Frcst I,1.5,A,TO 572,Yes
3,Winter 2024,00348486,20803,WN 2023,SI,643,1,Regular,Lecture,Instructional Skills,3.0,A+,SI 643,No
4,Winter 2024,00348486,39178,FA 2023,SI,539,1,Regular,Lecture,Web Design,3.0,A+,SI 539,No

Index(['CompletionTermDesc', 'Emplid', 'Crse ID', 'Term Descrshort', 'Subject',
       'Catalog Nbr', 'Class Section', 'Session Descrshort',
       'Crse Component Descrshort', 'Crse Descr', 'Unt Earned - Credits',
       'Crse Grade Off - Grade Earned', 'Course Code', 'Outside UMSI'],
      dtype='str')

In [50]:
# Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("-", "")
)

# Clean Course_Code
df["Course_Code"] = df["Course_Code"].astype(str).str.strip()

display(df.columns)

Index(['CompletionTermDesc', 'Emplid', 'Crse_ID', 'Term_Descrshort', 'Subject',
       'Catalog_Nbr', 'Class_Section', 'Session_Descrshort',
       'Crse_Component_Descrshort', 'Crse_Descr', 'Unt_Earned__Credits',
       'Crse_Grade_Off__Grade_Earned', 'Course_Code', 'Outside_UMSI'],
      dtype='str')

**Data Analysis**

In [51]:
# Unique students
all_students = set(df["Emplid"].unique())
print(f"Number of Students: {len(all_students)}")

# Unique courses
print(f"Number of Unique Courses: {df['Course_Code'].nunique()}")

# Most popular courses
print("Most Popular Courses:")
print(df["Course_Code"].value_counts().head(10))

Number of Students: 308
Number of Unique Courses: 302
Most Popular Courses:
Course_Code
SI 699    291
SI 501    271
SI 681    233
SI 539    193
SI 582    184
SI 588    183
SI 622    183
SI 506    183
SI 520    160
SI 505    137
Name: count, dtype: int64

**MTOP & Capstone Course Count**

In [52]:
print(f"Students with SI 697 or SI 698: {df[df['Course_Code'].isin(['SI 697', 'SI 698'])]['Emplid'].nunique()}")

print("Counts for SI 699, SI 697, SI 698:")
print(df["Course_Code"].value_counts().reindex(["SI 699", "SI 697", "SI 698"]))

Students with SI 697 or SI 698: 13
Counts for SI 699, SI 697, SI 698:
Course_Code
SI 699    291
SI 697     13
SI 698     13
Name: count, dtype: int64

In [53]:
# SI 699 students
si699_students = set(df.loc[df["Course_Code"] == "SI 699", "Emplid"])
print("SI 699:", len(si699_students))

SI 699: 290

In [54]:
df[df["Course_Code"] == "SI 699"]["Emplid"].value_counts().loc[lambda x: x > 1]

Emplid
74957450    2
Name: count, dtype: int64

**Find MTOP Students**

In [55]:
mtop_students = set(df.loc[df["Course_Code"].isin(["SI 697", "SI 698"]), "Emplid"])
print("MTOP:", mtop_students, len(mtop_students))

MTOP: {'30823513', '57754225', '45956646', '17960225', '13140458', '29291012', '78547794', '64018543', '76653762', '06981246', '15408298', '30771844', '64732339'} 13

**Find Students Who Have Taken Neither**

In [56]:
missing_students = all_students - (si699_students | mtop_students)
print("Missing Students:", missing_students, len(missing_students))

Missing Students: {'55283189', '19408190', '47867920', '48604860', '35417600', '53193575', '50952532'} 7

In [57]:
# Courseload for students who took neither SI 699 nor SI 697/698
df[df["Emplid"].isin(missing_students)].sort_values(["Emplid", "Course_Code"])

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,Unt_Earned__Credits,Crse_Grade_Off__Grade_Earned,Course_Code,Outside_UMSI
998,Winter 2024,19408190,13504,WN 2023,EAS,687,1,Regular,Lecture,Mod for LandscpePlan,4.0,A,EAS 687,Yes
1004,Winter 2024,19408190,42104,FA 2022,SI,501,1,Regular,Lecture,Contextual Inq,3.0,A-,SI 501,No
1008,Winter 2024,19408190,50164,FA 2022,SI,504,1,Regular,Lecture,"Servers, Shell,&Git",1.5,A,SI 504,No
1001,Winter 2024,19408190,21400,FA 2023,SI,520,1,Regular,Lecture,Graphic Design,3.0,A,SI 520,No
1002,Winter 2024,19408190,39178,FA 2022,SI,539,101,Regular,Lecture,Web Design,3.0,A,SI 539,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2939,Winter 2024,55283189,43863,WN 2023,SI,612,1,Regular,Lecture,Pervasv Interact Des,3.0,A-,SI 612,No
2934,Winter 2024,55283189,20401,WN 2023,SI,622,1,Regular,Lecture,Usab Eval & Needs,4.0,A,SI 622,No
2937,Winter 2024,55283189,41626,WN 2023,SI,664,1,Regular,Lecture,Database App Design,3.0,A,SI 664,No
2936,Winter 2024,55283189,40667,WN 2023,SI,681,1,Regular,Seminar,Intern/Field Seminar,6.0,S,SI 681,No
2943,Winter 2024,55283189,50136,FA 2022,UARTS,560,116,Regular,Laboratory,Grad ArtsEng Proj,2.0,A+,UARTS 560,Yes

In [58]:
# Combine MTOP and missing students to get the full list of students to exclude
exclude_students = mtop_students.union(missing_students)
print("Students to Exclude:", len(exclude_students))
exclude_students

Students to Exclude: 20

{'06981246',
 '13140458',
 '15408298',
 '17960225',
 '19408190',
 '29291012',
 '30771844',
 '30823513',
 '35417600',
 '45956646',
 '47867920',
 '48604860',
 '50952532',
 '53193575',
 '55283189',
 '57754225',
 '64018543',
 '64732339',
 '76653762',
 '78547794'}

In [59]:
# Check overlap between SI 699 and MTOP
overlap = si699_students & mtop_students
print("Overlap between SI 699 and MTOP:", len(overlap))
print(overlap)

Overlap between SI 699 and MTOP: 2
{'45956646', '64732339'}

In [60]:
df[df["Emplid"] == list(overlap)[0]].sort_values("Course_Code")  # inspect any overlap students

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,Unt_Earned__Credits,Crse_Grade_Off__Grade_Earned,Course_Code,Outside_UMSI
2339,Winter 2024,45956646,44798,WN 2023,ENTR,599,408,First 7 Wk,Lecture,Spec Topics Entr,1.0,A+,ENTR 599,Yes
2337,Winter 2024,45956646,42104,FA 2022,SI,501,1,Regular,Lecture,Contextual Inq,3.0,A,SI 501,No
2349,Winter 2024,45956646,50164,FA 2022,SI,504,1,Regular,Lecture,"Servers, Shell,&Git",1.5,B+,SI 504,No
2340,Winter 2024,45956646,47246,FA 2022,SI,506,1,Regular,Lecture,Programming I,3.0,B,SI 506,No
2341,Winter 2024,45956646,47640,WN 2023,SI,507,1,Regular,Lecture,Inter Programming,3.0,B,SI 507,No
2333,Winter 2024,45956646,21400,FA 2022,SI,520,2,Regular,Lecture,Graphic Design,3.0,A-,SI 520,No
2334,Winter 2024,45956646,39178,FA 2022,SI,539,1,Regular,Lecture,Web Design,3.0,B+,SI 539,No
2343,Winter 2024,45956646,48488,FA 2023,SI,559,1,Regular,Lecture,AR/VR Intro,3.0,A-,SI 559,No
2335,Winter 2024,45956646,42071,FA 2023,SI,563,1,Regular,Lecture,Game Theory,3.0,B+,SI 563,No
2346,Winter 2024,45956646,49601,WN 2023,SI,564,1,Regular,Lecture,SQL & Databases,1.5,A,SI 564,No
2350,Winter 2024,45956646,50663,WN 2024,SI,568,1,Regular,Lecture,Intro Appld Data Sci,1.5,B+,SI 568,No
2338,Winter 2024,45956646,44772,WN 2023,SI,582,1,Regular,Lecture,Intro Interac Design,3.0,A+,SI 582,No
2331,Winter 2024,45956646,17281,FA 2022,SI,588,2,Regular,Lecture,Fundamntls Hum Beh,3.0,A,SI 588,No
2351,Winter 2024,45956646,50983,WN 2024,SI,602,1,Regular,Lecture,Math for ApplDataSci,3.0,C,SI 602,No
2336,Winter 2024,45956646,42091,WN 2023,SI,618,1,Regular,Lecture,Data Man & Analysis,3.0,A+,SI 618,No
2332,Winter 2024,45956646,20934,WN 2023,SI,649,1,Regular,Lecture,Info Visualization,3.0,B+,SI 649,No
2330,Winter 2024,45956646,9732,FA 2023,SI,650,1,Regular,Lecture,Informatn Retrieval,3.0,E,SI 650,No
2344,Winter 2024,45956646,48500,FA 2023,SI,670,1,Regular,Lecture,Appld Machine Learng,3.0,B,SI 670,No
2345,Winter 2024,45956646,49365,FA 2023,SI,697,82,Regular,Ind Study,Master's Thesis 1,3.0,NR,SI 697,No
2342,Winter 2024,45956646,47901,WN 2024,SI,699,305,Regular,Lecture,MSI Mastery Courses,3.0,A,SI 699,No
2347,Winter 2024,45956646,50136,WN 2023,UARTS,560,103,Regular,Laboratory,Grad ArtsEng Proj,2.0,,UARTS 560,Yes
2348,Winter 2024,45956646,50136,FA 2023,UARTS,560,103,Regular,Laboratory,Grad ArtsEng Proj,2.0,A,UARTS 560,Yes

In [61]:
df[df["Emplid"] == list(overlap)[1]].sort_values("Course_Code")  # inspect any overlap students

,CompletionTermDesc,Emplid,Crse_ID,Term_Descrshort,Subject,Catalog_Nbr,Class_Section,Session_Descrshort,Crse_Component_Descrshort,Crse_Descr,Unt_Earned__Credits,Crse_Grade_Off__Grade_Earned,Course_Code,Outside_UMSI
3596,Winter 2024,64732339,49693,WN 2023,DIGITAL,458,1,Regular,Seminar,Seminar in DS,3.0,W,DIGITAL 458,Yes
3588,Winter 2024,64732339,41044,WN 2022,ELI,510,1,Regular,Lecture,Acad Rdg&Vocab,2.0,S,ELI 510,Yes
3583,Winter 2024,64732339,38618,FA 2022,ELI,522,1,Regular,Lecture,Res Paper Writing,2.0,S,ELI 522,Yes
3575,Winter 2024,64732339,14796,FA 2021,ELI,531,1,Regular,Lecture,Lang&Comm I,1.0,S,ELI 531,Yes
3577,Winter 2024,64732339,16655,WN 2022,ELI,538,2,Regular,Lecture,Pron in Context,1.0,S,ELI 538,Yes
3592,Winter 2024,64732339,47695,FA 2022,ELI,592,1,Regular,Lecture,Topics in EAP,1.0,S,ELI 592,Yes
3587,Winter 2024,64732339,40779,FA 2022,ENGLISH,580,1,Regular,Seminar,Disability Studies,3.0,A,ENGLISH 580,Yes
3590,Winter 2024,64732339,42104,FA 2021,SI,501,1,Regular,Lecture,Contextual Inq,3.0,A+,SI 501,No
3599,Winter 2024,64732339,50164,FA 2021,SI,504,1,Regular,Lecture,"Servers, Shell,&Git",1.5,A+,SI 504,No
3582,Winter 2024,64732339,21400,WN 2024,SI,520,3,Regular,Laboratory,Graphic Design,3.0,A,SI 520,No
3584,Winter 2024,64732339,39178,WN 2022,SI,539,1,Regular,Lecture,Web Design,3.0,A,SI 539,No
3576,Winter 2024,64732339,16607,FA 2021,SI,544,1,Regular,Lecture,Intr Stat&Data Analy,3.0,A+,SI 544,No
3591,Winter 2024,64732339,44772,FA 2021,SI,582,3,Regular,Lecture,Intro Interac Design,3.0,A+,SI 582,No
3578,Winter 2024,64732339,17281,FA 2021,SI,588,2,Regular,Lecture,Fundamntls Hum Beh,3.0,A+,SI 588,No
3589,Winter 2024,64732339,42091,FA 2022,SI,618,1,Regular,Lecture,Data Man & Analysis,3.0,A,SI 618,No
3579,Winter 2024,64732339,20401,WN 2024,SI,622,1,Regular,Lecture,Usab Eval & Needs,4.0,A+,SI 622,No
3585,Winter 2024,64732339,39979,WN 2022,SI,623,1,Regular,Seminar,Res Meth Info Prof,3.0,A+,SI 623,No
3580,Winter 2024,64732339,20934,WN 2022,SI,649,1,Regular,Lecture,Info Visualization,3.0,A+,SI 649,No
3586,Winter 2024,64732339,40667,WN 2022,SI,681,1,Regular,Seminar,Intern/Field Seminar,6.0,S,SI 681,No
3581,Winter 2024,64732339,21050,WN 2022,SI,691,128,Regular,Ind Study,Independent Study,3.0,A,SI 691,No
3595,Winter 2024,64732339,49365,FA 2022,SI,697,131,Regular,Ind Study,Master's Thesis 1,3.0,S,SI 697,No
3594,Winter 2024,64732339,49040,WN 2023,SI,698,131,Regular,Seminar,Master's Thesis 2,3.0,E,SI 698,No
3593,Winter 2024,64732339,47901,WN 2024,SI,699,501,Regular,Lecture,MSI Mastery Courses,3.0,A,SI 699,No
3600,Winter 2024,64732339,50705,WN 2023,SI,719,1,Regular,Lecture,Science Tech&Med,3.0,B-,SI 719,No
3597,Winter 2024,64732339,50136,WN 2022,UARTS,560,116,Regular,Laboratory,Grad ArtsEng Proj,2.0,A,UARTS 560,Yes
3598,Winter 2024,64732339,50136,FA 2022,UARTS,560,116,Regular,Laboratory,Grad ArtsEng Proj,2.0,A,UARTS 560,Yes

**Narrow Dataset to Only Students who Have Taken SI 699**

In [62]:
exclude_students = mtop_students.union(missing_students)
 
df_filtered = df[~df["Emplid"].isin(exclude_students)].copy()
print(f"\nFiltered student count: {df_filtered['Emplid'].nunique()}")

Filtered student count: 288

In [63]:
si699_rows = df[df["Course_Code"] == "SI 699"]
print("SI 699 rows:", len(si699_rows))
print("SI 699 unique students:", si699_rows["Emplid"].nunique())

SI 699 rows: 291
SI 699 unique students: 290

In [64]:
si699_rows["Emplid"].value_counts().loc[lambda x: x > 1]
# NOTE (2024): SI 699 has 291 rows but 290 unique students — one student took it twice.
# This does not affect analysis since all counts use .nunique() throughout.

Emplid
74957450    2
Name: count, dtype: int64

In [65]:
overlap = si699_students & mtop_students
print("Overlap between SI 699 and MTOP:", len(overlap))
print(overlap)

Overlap between SI 699 and MTOP: 2
{'45956646', '64732339'}

**Define Required Courses by Track**

In [66]:
df_filtered = df[~df["Emplid"].isin(exclude_students)].copy()
print(f"\nFiltered student count: {df_filtered['Emplid'].nunique()}")

Filtered student count: 288

In [67]:
track_required_courses = {
    "BDA": [
        "SI 507",   # fixed — BDA-unique
        "SI 544",   # fixed — BDA-unique
        "SI 568",   # fixed — BDA-unique
        "SI 602",   # fixed — new FA 2022 BDA req
        "SI 618",   # fixed — BDA-unique
        "SI 670",   # pick-1 alternate
        "SI 671",   # pick-1 alternate
    ],
    "UX": [
        "SI 520",   # only UX-unique fixed req (SI 539/582/588/622 overlap with UCAD)
    ],
    "UCAD": [
        "SI 579",   # fixed — UCAD-unique
        "SI 664",   # pick-1 alternate
        "SI 669",   # pick-1 alternate
    ],
    # LAKES covers CIC, MSC, and Digital Curation — all share SI 699 mastery course
    "LAKES": [
        # Shared across all three LAKES sub-pathways
        "SI 510",   # fixed in CIC, MSC, and Digital Curation
        "SI 580",   # pick-1 across CIC, MSC, and Digital Curation
        "SI 647",   # pick-1 across CIC, MSC, and Digital Curation
        # CIC-unique
        "SI 547",   # fixed in CIC only
        # Digital Curation-unique fixed reqs
        "SI 666",   # fixed in DC; also pick-4 in MSC
        "SI 667",   # fixed in DC; also pick-4 in MSC
        "SI 676",   # fixed in DC only
    ]
}

In [68]:
# Create flag columns FIRST
for track, courses in track_required_courses.items():
    df_filtered[f"{track}_Flag"] = df_filtered["Course_Code"].isin(courses).astype(int)

In [69]:
# Then aggregate
track_counts = df_filtered.groupby("Emplid").agg(
    BDA_Count=("BDA_Flag", "sum"),
    UX_Count=("UX_Flag", "sum"),
    LAKES_Count=("LAKES_Flag", "sum"),
    UCAD_Count=("UCAD_Flag", "sum")
)
track_counts.head()

          BDA_Count  UX_Count  LAKES_Count  UCAD_Count
Emplid
00348486          6         0            0           1
01044544          0         1            0           2
01416822          3         0            0           0
01497390          0         0            1           3
01814680          0         1            0           1

In [70]:
# Use the counts of required courses ("votes") to infer the most likely track
vote_cols = ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count"]

In [71]:
# total votes + max vote per student
total_votes = track_counts[vote_cols].sum(axis=1)
max_vote    = track_counts[vote_cols].max(axis=1)

In [72]:
# how many tracks tied for the max
number_at_max = track_counts[vote_cols].eq(max_vote, axis=0).sum(axis=1)

In [73]:
# best guess track
best_guess = (
    track_counts[vote_cols]
    .idxmax(axis=1)
    .str.replace("_Count", "", regex=False)
)

In [74]:
# Initialize all students as "Unknown", then assign tracks based on vote results
track_counts["Inferred_Track"] = "Unknown"

In [75]:
# 0 votes → Zero-track
track_counts.loc[total_votes.eq(0), "Inferred_Track"] = "Zero-track"

In [76]:
# Tie
tie_mask = total_votes.gt(0) & number_at_max.gt(1)
track_counts.loc[tie_mask, "Inferred_Track"] = "Tie"

In [77]:
# non-ties → assign best guess
assign_mask = total_votes.gt(0) & number_at_max.eq(1)
track_counts.loc[assign_mask, "Inferred_Track"] = best_guess[assign_mask]

In [78]:
print(track_counts["Inferred_Track"].value_counts())

Inferred_Track
UX            80
BDA           68
LAKES         46
UCAD          43
Tie           34
Zero-track    17
Name: count, dtype: int64

**Resolve Ties**

In [79]:
# Drop point columns if they already exist (makes cell safe to rerun)
point_cols = ["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]
track_counts = track_counts.drop(columns=[c for c in point_cols if c in track_counts.columns])

In [80]:
# UX — all fixed reqs + full pick-2 selective list per FA 2022 UX PDF
UX_TIEBREAK = [
    "SI 520",  # fixed
    "SI 539",  # fixed
    "SI 582",  # fixed
    "SI 588",  # fixed
    "SI 622",  # fixed
    "SI 529",  # pick-2 selective
    "SI 552",  # pick-2 selective
    "SI 559",  # pick-2 selective
    "SI 612",  # pick-2 selective
    "SI 616",  # pick-2 selective
    "SI 658",  # pick-2 selective
    "SI 659",  # pick-2 selective
    "SI 684",  # pick-2 selective
]
 
# UCAD — UCAD-distinguishing courses only (SI 504/539/582/588/622 overlap with UX/other)
UCAD_TIEBREAK = [
    "SI 579",  # fixed — UCAD-unique
    "SI 664",  # pick-1 alternate
    "SI 669",  # pick-1 alternate
]
 
# BDA — pick-2 options + pick-1 options + BDA-distinguishing fixed reqs
# SI 561 included as NLP alternative to SI 630 per FA 2022 BDA PDF
BDA_TIEBREAK = [
    "SI 608",  # pick-2 selective
    "SI 630",  # pick-2 selective
    "SI 649",  # pick-2 selective
    "SI 650",  # pick-2 selective
    "SI 670",  # pick-1 alternate
    "SI 671",  # pick-1 alternate
    "SI 568",  # fixed
    "SI 602",  # fixed — new FA 2022 req
    "SI 561",  # NLP alternative to SI 630 per FA 2022 BDA PDF
]
 
# LAKES — covers all three sub-pathways: CIC, MSC, and Digital Curation
# Excludes courses that overlap with UX (SI 539, SI 622) or BDA (SI 649)
# SI 638 REMOVED — not in any FA 2022 PDF
# SI 530 REMOVED — FA 2021 only (SI 626 already covers management signal)
# SI 639 ADDED — Digital Curation pick-2 and MSC recommended elective
# SI 581 ADDED — recommended elective in both CIC and MSC
# SI 549 ADDED — recommended elective in CIC
LAKES_TIEBREAK = [
    # Shared across CIC, MSC, and/or Digital Curation
    "SI 623",  # fixed in CIC and MSC
    "SI 626",  # pick-3 in CIC; pick-4 in MSC
    "SI 632",  # pick-3 in CIC; pick-4 in MSC
    "SI 633",  # pick-3 in CIC; pick-4 in MSC; pick-2 in Digital Curation
    "SI 585",  # pick-4 in MSC; pick-2 in Digital Curation; recommended in CIC
    "SI 519",  # recommended elective in CIC, MSC, and Digital Curation
    "SI 552",  # recommended in CIC and MSC; pick-2 selective in UX (weak LAKES signal)
    "SI 581",  # recommended elective in CIC and MSC
    # CIC-specific
    "SI 547",  # fixed in CIC only (also in primary signals)
    "SI 538",  # pick-3 in CIC only
    "SI 643",  # pick-3 in CIC only
    "SI 549",  # recommended elective in CIC only
    # MSC-specific
    "SI 583",  # pick-4 in MSC only
    # Digital Curation-specific
    "SI 639",  # pick-2 in Digital Curation (paired with SI 564); recommended in MSC
]

In [81]:
df_filtered["UX_Points"]    = df_filtered["Course_Code"].isin(UX_TIEBREAK).astype(int)
df_filtered["UCAD_Points"]  = df_filtered["Course_Code"].isin(UCAD_TIEBREAK).astype(int)
df_filtered["BDA_Points"]   = df_filtered["Course_Code"].isin(BDA_TIEBREAK).astype(int)
df_filtered["LAKES_Points"] = df_filtered["Course_Code"].isin(LAKES_TIEBREAK).astype(int)

In [82]:
points = df_filtered.groupby("Emplid")[
    ["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]
].sum()
 
track_counts = track_counts.join(points, how="left")
track_counts[["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]] = (
    track_counts[["UX_Points", "UCAD_Points", "BDA_Points", "LAKES_Points"]].fillna(0)
)

In [83]:
# Reassign tie students using all four track signals
tie_mask = track_counts["Inferred_Track"].isin(["Tie", "Manual"])
point_cols_map = ["BDA_Points", "UX_Points", "LAKES_Points", "UCAD_Points"]
col_to_track = {
    "BDA_Points":   "BDA",
    "UX_Points":    "UX",
    "LAKES_Points": "LAKES",
    "UCAD_Points":  "UCAD"
}

In [84]:
for idx in track_counts[tie_mask].index:
    row = track_counts.loc[idx, point_cols_map]
    max_pts = row.max()
    if max_pts == 0 or (row == max_pts).sum() > 1:
        track_counts.loc[idx, "Inferred_Track"] = "Tie"
    else:
        track_counts.loc[idx, "Inferred_Track"] = col_to_track[row.idxmax()]
 
print(track_counts["Inferred_Track"].value_counts())

Inferred_Track
UX            112
BDA            68
LAKES          46
UCAD           43
Zero-track     17
Tie             2
Name: count, dtype: int64

In [85]:
tie_ids = track_counts[track_counts["Inferred_Track"] == "Tie"].index
for emplid in tie_ids:
    courses = sorted(df_filtered[df_filtered["Emplid"] == emplid]["Course_Code"].unique())
    print(f"\nStudent: {emplid}")
    print(f"Courses: {courses}")
    print(track_counts.loc[emplid, ["BDA_Count", "UX_Count", "LAKES_Count", "UCAD_Count",
                                     "BDA_Points", "UX_Points", "LAKES_Points", "UCAD_Points"]])

Student: 21257670
Courses: ['SI 501', 'SI 520', 'SI 540', 'SI 547', 'SI 552', 'SI 559', 'SI 643', 'SI 690', 'SI 699']
BDA_Count       0
UX_Count        1
LAKES_Count     1
UCAD_Count      0
BDA_Points      0
UX_Points       3
LAKES_Points    3
UCAD_Points     0
Name: 21257670, dtype: int64

Student: 59253647
Courses: ['SI 501', 'SI 510', 'SI 520', 'SI 538', 'SI 547', 'SI 581', 'SI 583', 'SI 616', 'SI 684', 'SI 699']
BDA_Count       0
UX_Count        2
LAKES_Count     2
UCAD_Count      0
BDA_Points      0
UX_Points       4
LAKES_Points    4
UCAD_Points     0
Name: 59253647, dtype: int64

In [86]:
# MANUAL OVERRIDES FOR TIE STUDENTS
tie_overrides = {
    # "EMPLID": "TRACK",   # reason: ...
    "21257670": "UX",    # took SI 520, SI 559, SI 616 — UX selectives outweigh CIC
    "59253647": "UX", # took SI 547, SI 643, SI 623 — clear CIC pattern
}

for emplid, track in tie_overrides.items():
    track_counts.loc[emplid, "Inferred_Track"] = track

# Confirm ties are resolved before moving on
remaining_ties = track_counts[track_counts["Inferred_Track"] == "Tie"]
print(f"Remaining ties after manual override: {len(remaining_ties)}")
assert len(remaining_ties) == 0, \
    f"Still have unresolved ties: {list(remaining_ties.index)} — fill in tie_overrides above!"

Remaining ties after manual override: 0

**Resolve Zero-Track**

In [87]:
zero_ids = track_counts[track_counts["Inferred_Track"] == "Zero-track"].index
 
zero_courses = df_filtered[df_filtered["Emplid"].isin(zero_ids)]
print("Most common courses among zero-track students:")
print(zero_courses["Course_Code"].value_counts().head(20))

Most common courses among zero-track students:
Course_Code
SI 699      17
SI 690      15
SI 501      14
SI 506      11
SI 612      10
SI 559      10
SI 622      10
SI 539      10
SI 588       9
SI 582       9
SI 552       9
SI 681       8
SI 616       7
SI 658       7
SI 684       6
SI 538       6
SI 511       6
ENTR 500     5
SI 505       5
ENTR 560     5
Name: count, dtype: int64

In [88]:
# Soft-vote signal lists — mirrors primary + tiebreak logic above
zero_track_signals = {
    "UX": [
        "SI 520",  # fixed
        "SI 539",  # fixed
        "SI 582",  # fixed
        "SI 588",  # fixed
        "SI 622",  # fixed
        "SI 529",  # pick-2 selective
        "SI 552",  # pick-2 selective
        "SI 559",  # pick-2 selective
        "SI 612",  # pick-2 selective
        "SI 616",  # pick-2 selective
        "SI 658",  # pick-2 selective
        "SI 659",  # pick-2 selective
        "SI 684",  # pick-2 selective
    ],
    "UCAD": [
        "SI 579",  # fixed — UCAD-unique
        "SI 664",  # pick-1 alternate
        "SI 669",  # pick-1 alternate
    ],
    "BDA": [
        "SI 608",  # pick-2 selective
        "SI 630",  # pick-2 selective
        "SI 649",  # pick-2 selective
        "SI 650",  # pick-2 selective
        "SI 670",  # pick-1 alternate
        "SI 671",  # pick-1 alternate
        "SI 568",  # fixed
        "SI 602",  # fixed — new FA 2022 req
        "SI 561",  # NLP alternative to SI 630 (consistent with BDA_TIEBREAK)
    ],
    # LAKES covers all three sub-pathways: CIC, MSC, and Digital Curation
    "LAKES": [
        # Shared across all three LAKES sub-pathways
        "SI 510",  # fixed in CIC, MSC, and Digital Curation
        "SI 580",  # pick-1 across CIC, MSC, and Digital Curation
        "SI 647",  # pick-1 across CIC, MSC, and Digital Curation
        "SI 623",  # fixed in CIC and MSC
        "SI 626",  # pick-3 in CIC; pick-4 in MSC
        "SI 632",  # pick-3 in CIC; pick-4 in MSC
        "SI 633",  # pick-3 in CIC; pick-4 in MSC; pick-2 in Digital Curation
        "SI 585",  # pick-4 in MSC; pick-2 in Digital Curation; recommended in CIC
        "SI 519",  # recommended in CIC, MSC, and Digital Curation
        "SI 552",  # recommended in CIC and MSC
        "SI 581",  # recommended in CIC and MSC
        # CIC-specific
        "SI 547",  # fixed in CIC only
        "SI 538",  # pick-3 in CIC only
        "SI 643",  # pick-3 in CIC only
        "SI 549",  # recommended in CIC only
        # MSC-specific
        "SI 583",  # pick-4 in MSC only
        # Digital Curation-specific
        "SI 666",  # fixed in DC; also pick-4 in MSC (also in primary signals)
        "SI 667",  # fixed in DC; also pick-4 in MSC (also in primary signals)
        "SI 676",  # fixed in DC only (also in primary signals)
        "SI 639",  # pick-2 in Digital Curation; recommended in MSC
    ]
}

In [89]:
soft_votes = df_filtered[df_filtered["Emplid"].isin(zero_ids)].copy()
for track, courses in zero_track_signals.items():
    soft_votes[f"{track}_soft"] = soft_votes["Course_Code"].isin(courses).astype(int)
 
soft_votes = soft_votes.groupby("Emplid")[
    ["UX_soft", "UCAD_soft", "BDA_soft", "LAKES_soft"]
].sum()
 
print(soft_votes)

          UX_soft  UCAD_soft  BDA_soft  LAKES_soft
Emplid
06415334        4          0         0           1
12145979        3          0         1           1
15720118        7          0         0           1
31641295        3          0         0           0
31889818        9          0         0           1
32636557        2          0         0           0
34919182        6          0         1           0
37555260        7          0         0           1
51398363        6          0         0           2
58434981        4          0         0           1
63529052        3          0         0           1
64400569        9          0         0           3
67989589        6          0         0           1
74959836        7          0         0           2
76259359        3          0         0           1
76452394        8          0         0           2
90246112        4          0         0           2

In [90]:
# Check for any students with 0 soft signals (need manual review)
zero_soft_ids = soft_votes[(soft_votes == 0).all(axis=1)].index.tolist()
print(f"Students with 0 soft signals: {zero_soft_ids}")

Students with 0 soft signals: []

**Final Check**

In [91]:
# Build soft assignments for zero-track students
soft_assignments = {}

for emplid, row in soft_votes.iterrows():
    scores = {
        'BDA': row['BDA_soft'],
        'UX': row['UX_soft'],
        'UCAD': row['UCAD_soft'],
        'LAKES': row['LAKES_soft']
    }
    max_score = max(scores.values())
    if max_score > 0:
        top_tracks = [t for t, s in scores.items() if s == max_score]
        if len(top_tracks) == 1:
            soft_assignments[emplid] = top_tracks[0]
        # ties with equal soft scores left unresolved — handle manually

In [92]:
for emplid, track in soft_assignments.items():
    track_counts.loc[emplid, "Inferred_Track"] = track
    
print(track_counts["Inferred_Track"].value_counts())
 
assert "Zero-track" not in track_counts["Inferred_Track"].values, \
    "Still have zero-track students — check soft_assignments!"
 
remaining_ties = track_counts[track_counts["Inferred_Track"] == "Tie"]
if len(remaining_ties) > 0:
    print(f"\nWARNING: {len(remaining_ties)} unresolved tie student(s). "
          "Add a manual override in the section above.")
    for emplid in remaining_ties.index:
        courses = sorted(df_filtered[df_filtered["Emplid"] == emplid]["Course_Code"].unique())
        print(f"  {emplid}: {courses}")
        print(f"  {track_counts.loc[emplid, ['BDA_Count','UX_Count','LAKES_Count','UCAD_Count','BDA_Points','UX_Points','LAKES_Points','UCAD_Points']]}\n")

Inferred_Track
UX       131
BDA       68
LAKES     46
UCAD      43
Name: count, dtype: int64

In [93]:
track_labels   = track_counts.reset_index()[["Emplid", "Inferred_Track"]]
df_with_tracks = df_filtered.merge(track_labels, on="Emplid", how="left")
 
print(df_with_tracks["Inferred_Track"].value_counts())
print(f"Unique students: {df_with_tracks['Emplid'].nunique()}")

Inferred_Track
UX       2115
BDA      1154
LAKES     783
UCAD      741
Name: count, dtype: int64
Unique students: 288

**Elective Analysis**

In [94]:
REQUIRED = {
    "BDA": {
        "SI 504",   # fixed
        "SI 507",   # fixed
        "SI 544",   # fixed
        "SI 568",   # fixed
        "SI 602",   # fixed (new FA 2022 req)
        "SI 618",   # fixed
        "SI 670",   # pick-1 option
        "SI 671",   # pick-1 option
        "SI 608",   # pick-2 option
        "SI 630",   # pick-2 option
        "SI 649",   # pick-2 option
        "SI 650",   # pick-2 option
        "SI 561",   # pick-2 NLP alt to SI 630
    },
    "UX": {
        "SI 520",   # fixed
        "SI 539",   # fixed
        "SI 582",   # fixed
        "SI 588",   # fixed
        "SI 622",   # fixed
        "SI 529",   # pick-2 option
        "SI 552",   # pick-2 option
        "SI 559",   # pick-2 option
        "SI 612",   # pick-2 option
        "SI 616",   # pick-2 option
        "SI 658",   # pick-2 option
        "SI 659",   # pick-2 option
        "SI 684",   # pick-2 option
    },
    "UCAD": {
        "SI 504",   # fixed
        "SI 539",   # fixed
        "SI 579",   # fixed
        "SI 582",   # fixed
        "SI 588",   # fixed
        "SI 622",   # fixed
        "SI 664",   # pick-1 option
        "SI 669",   # pick-1 option
    },
    # LAKES covers CIC, MSC, and Digital Curation — all pick options included
    "LAKES": {
        # Shared fixed
        "SI 510",   # fixed in CIC, MSC, Digital Curation
        "SI 580",   # pick-1 across all three
        "SI 647",   # pick-1 across all three
        # CIC fixed + picks
        "SI 547",   # fixed in CIC
        "SI 623",   # fixed in CIC and MSC
        "SI 538",   # pick-3 in CIC
        "SI 626",   # pick-3 in CIC; pick-4 in MSC
        "SI 632",   # pick-3 in CIC; pick-4 in MSC
        "SI 633",   # pick-3 in CIC; pick-4 in MSC; pick-2 in DC
        "SI 643",   # pick-3 in CIC
        # MSC-specific picks
        "SI 583",   # pick-4 in MSC
        "SI 585",   # pick-4 in MSC; pick-2 in DC
        "SI 666",   # pick-4 in MSC; fixed in DC
        "SI 667",   # pick-4 in MSC; fixed in DC
        # Digital Curation fixed + picks
        "SI 504",   # fixed in DC (shared with BDA/UCAD)
        "SI 676",   # fixed in DC
        "SI 539",   # pick-2 in DC (shared with UX/UCAD)
        "SI 564",   # pick-2 in DC (paired with SI 639)
        "SI 639",   # pick-2 in DC (paired with SI 564)
        "SI 622",   # pick-2 in DC (shared with UX)
    }
}

In [95]:
UNIVERSAL_EXCLUDE = {
    "SI 501",   # core — Contextual Inquiry
    "SI 505",   # remedial/bridge course
    "SI 506",   # core — Programming I
    "SI 681",   # internship
    "SI 690",   # internship
    "SI 699",   # mastery/capstone
}

In [96]:
# SI Elective Analysis
results = {}
for track in ["BDA", "UX", "UCAD", "LAKES"]:
    exclude    = UNIVERSAL_EXCLUDE | REQUIRED[track]
    n_students = (track_counts["Inferred_Track"] == track).sum()
 
    track_df = df_with_tracks[
        (df_with_tracks["Inferred_Track"] == track) &
        (~df_with_tracks["Course_Code"].isin(exclude))
    ]
 
    elective_counts = (
        track_df.groupby("Course_Code")["Emplid"]
        .nunique()
        .sort_values(ascending=False)
        .rename("Student_Count")
        .reset_index()
    )
 
    elective_counts["Pct_of_Track"] = (
        elective_counts["Student_Count"] / n_students * 100
    ).round(1)
 
    results[track] = elective_counts
 
    print(f"\n── {track} (n={n_students} students) ──────────────────")
    print(elective_counts.head(10).to_string(index=False))

── BDA (n=68 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 564             51          75.0
     SI 664             39          57.4
     SI 539             20          29.4
     SI 563             14          20.6
     SI 631             12          17.6
     SI 579             11          16.2
     SI 588             11          16.2
     SI 658              8          11.8
     SI 582              6           8.8
     SI 643              5           7.4

── UX (n=131 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 511             49          37.4
     SI 538             37          28.2
     SI 504             26          19.8
     SI 594             24          18.3
   ENTR 500             19          14.5
   ENTR 560             19          14.5
     SI 631             16          12.2
     SI 579             15          11.5
     SI 564             15          11.5
     SI 649             14          10.7

── UCAD (n=43 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 612             19          44.2
     SI 507             19          44.2
     SI 559             18          41.9
     SI 564             18          41.9
     SI 520             17          39.5
     SI 658             17          39.5
     SI 631             17          39.5
     SI 511             12          27.9
     SI 594              9          20.9
     SI 649              8          18.6

── LAKES (n=46 students) ──────────────────
Course_Code  Student_Count  Pct_of_Track
     SI 519             24          52.2
     SI 581             16          34.8
     SI 552             13          28.3
     SI 582             12          26.1
     SI 588              8          17.4
     SI 520              8          17.4
     SI 664              6          13.0
     SI 658              5          10.9
     SI 511              4           8.7
     SI 529              4           8.7

In [97]:
# Outside UMSI Electives
outside_results = {}
for track in ["BDA", "UX", "UCAD", "LAKES"]:
    exclude    = UNIVERSAL_EXCLUDE | REQUIRED[track]
    n_students = (track_counts["Inferred_Track"] == track).sum()
 
    outside_df = df_with_tracks[
        (df_with_tracks["Inferred_Track"] == track) &
        (~df_with_tracks["Course_Code"].isin(exclude)) &
        (df_with_tracks["Outside_UMSI"] == "Yes")
    ]
 
    outside_counts = (
        outside_df.groupby(["Course_Code", "Crse_Descr"])["Emplid"]
        .nunique()
        .sort_values(ascending=False)
        .rename("Student_Count")
        .reset_index()
    )
 
    outside_counts["Pct_of_Track"] = (
        outside_counts["Student_Count"] / n_students * 100
    ).round(1)
 
    outside_results[track] = outside_counts
 
    print(f"\n── {track} (n={n_students} students) ──────────────────")
    print(outside_counts.head(11).to_string(index=False))

── BDA (n=68 students) ──────────────────
Course_Code           Crse_Descr  Student_Count  Pct_of_Track
   EECS 402     Prog for Sci&Eng              4           5.9
  STATS 513  Regress&Data Analys              4           5.9
     TO 512  Decsn Supprt Sprdsh              3           4.4
   ENTR 500  Intro to Innovation              3           4.4
    MKT 608  Pricing Analy&Strat              3           4.4
   ENTR 599     Spec Topics Entr              2           2.9
   EECS 598       Special Topics              2           2.9
   EECS 545  Machine Learn (CSE)              2           2.9
   EECS 501     Prob&Random Proc              2           2.9
  STATS 500 Stat Learn I:Regress              2           2.9
    IOE 561      Risk Analysis I              2           2.9

── UX (n=131 students) ──────────────────
 Course_Code           Crse_Descr  Student_Count  Pct_of_Track
    ENTR 500  Intro to Innovation             19          14.5
    ENTR 560 Proj Mgmt Consulting             19          14.5
    ENTR 550 Interpersonal Skills             13           9.9
      TO 548        Integ Pro Dev             11           8.4
     IOE 548         Int Prod Dev             11           8.4
   UARTS 560    Grad ArtsEng Proj             10           7.6
    ENTR 599     Spec Topics Entr              9           6.9
WELLNESS 512      Yoga Performers              7           5.3
      BA 657                 LBLE              7           5.3
      BA 656                 LBLE              6           4.6
      BA 670       +Impact Studio              6           4.6

── UCAD (n=43 students) ──────────────────
Course_Code           Crse_Descr  Student_Count  Pct_of_Track
   ENTR 560 Proj Mgmt Consulting              6          14.0
   ENTR 599     Spec Topics Entr              5          11.6
  UARTS 560    Grad ArtsEng Proj              4           9.3
   EDUC 618      XR for Learning              2           4.7
   ENTR 390     Spec Topics Entr              2           4.7
   ARCH 509  Experimental Course              2           4.7
   ENTR 550 Interpersonal Skills              2           4.7
    ELI 534   Dis&Oral Argumentn              2           4.7
   EECS 402     Prog for Sci&Eng              2           4.7
   ENGR 599     Spec Topics Engr              2           4.7
MIDEAST 434            Shahnameh              1           2.3

── LAKES (n=46 students) ──────────────────
Course_Code           Crse_Descr  Student_Count  Pct_of_Track
MUSICOL 503         Mus Bibliogr              2           4.3
ENGLISH 578     Creative Writing              2           4.3
HISTORY 642 PreMod European Hist              2           4.3
  UARTS 560    Grad ArtsEng Proj              1           2.2
     TO 640  Big Data Mgmt Tools              1           2.2
     HS 502 Policy Politics Hlth              1           2.2
    IOE 548         Int Prod Dev              1           2.2
 MILSCI 301     Lead Small Org I              1           2.2
 MILSCI 302    Lead Small Org II              1           2.2
 MILSCI 401         Ldrshp & Mgt              1           2.2
 MILSCI 402      Mil Prof&Ethics              1           2.2

In [98]:
df_with_tracks["Outside_UMSI"].value_counts()

Outside_UMSI
No     4323
Yes     470
Name: count, dtype: int64

In [99]:
# Export full elective list for all tracks — for student-facing course directory
import json

full_course_map = {}

for track, df_result in results.items():
    # Only include SI courses (not outside UMSI)
    si_only = df_result[df_result['Course_Code'].str.startswith('SI ')]
    for _, row in si_only.iterrows():
        code = row['Course_Code']
        name = row.get('Crse_Descr') or row.get('Crse Descr') or ''
        if code not in full_course_map:
            full_course_map[code] = {'name': name, 'tracks': []}
        if track not in full_course_map[code]['tracks']:
            full_course_map[code]['tracks'].append(track)

# Print as JavaScript array ready to paste into your HTML file
print('const allCourses = [')
for code in sorted(full_course_map.keys(), key=lambda x: int(x.split()[1])):
    info = full_course_map[code]
    tracks = sorted([t.lower() for t in info['tracks']])
    tracks_str = ', '.join(f"'{t}'" for t in tracks)
    name = info['name'].replace("'", "\\'")
    print(f"  {{ code: '{code}', name: '{name}', tracks: [{tracks_str}] }},")
print('];')

const allCourses = [
  { code: 'SI 311', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 504', name: '', tracks: ['ux'] },
  { code: 'SI 507', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 510', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 511', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 519', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 520', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 521', name: '', tracks: ['ux'] },
  { code: 'SI 529', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 530', name: '', tracks: ['lakes'] },
  { code: 'SI 534', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 536', name: '', tracks: ['bda'] },
  { code: 'SI 538', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 539', name: '', tracks: ['bda'] },
  { code: 'SI 540', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 542', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 544', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 547', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 548', name: '', tracks: ['lakes', 'ux'] },
  { code: 'SI 549', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 552', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 554', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 559', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 563', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 564', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 579', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 581', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 582', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 583', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 588', name: '', tracks: ['bda', 'lakes'] },
  { code: 'SI 591', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 594', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 605', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 608', name: '', tracks: ['ucad'] },
  { code: 'SI 610', name: '', tracks: ['ux'] },
  { code: 'SI 611', name: '', tracks: ['bda'] },
  { code: 'SI 612', name: '', tracks: ['lakes', 'ucad'] },
  { code: 'SI 616', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 617', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 618', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 622', name: '', tracks: ['bda'] },
  { code: 'SI 623', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 624', name: '', tracks: ['bda'] },
  { code: 'SI 626', name: '', tracks: ['bda'] },
  { code: 'SI 627', name: '', tracks: ['ux'] },
  { code: 'SI 630', name: '', tracks: ['ucad'] },
  { code: 'SI 631', name: '', tracks: ['bda', 'lakes', 'ucad', 'ux'] },
  { code: 'SI 639', name: '', tracks: ['bda', 'ucad'] },
  { code: 'SI 643', name: '', tracks: ['bda', 'ucad', 'ux'] },
  { code: 'SI 644', name: '', tracks: ['bda'] },
  { code: 'SI 649', name: '', tracks: ['lakes', 'ucad', 'ux'] },
  { code: 'SI 650', name: '', tracks: ['ucad'] },
  { code: 'SI 652', name: '', tracks: ['bda'] },
  { code: 'SI 657', name: '', tracks: ['ucad', 'ux'] },
  { code: 'SI 658', name: '', tracks: ['bda', 'lakes', 'ucad'] },
  { code: 'SI 659', name: '', tracks: ['ucad'] },
  { code: 'SI 660', name: '', tracks: ['ux'] },
  { code: 'SI 661', name: '', tracks: ['lakes'] },
  { code: 'SI 664', name: '', tracks: ['bda', 'lakes', 'ux'] },
  { code: 'SI 667', name: '', tracks: ['bda', 'ux'] },
  { code: 'SI 669', name: '', tracks: ['bda'] },
  { code: 'SI 684', name: '', tracks: ['lakes', 'ucad'] },
  { code: 'SI 686', name: '', tracks: ['bda'] },
  { code: 'SI 688', name: '', tracks: ['ux'] },
  { code: 'SI 691', name: '', tracks: ['bda', 'ucad', 'ux'] },
];